apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oathkeeper

commonLabels:
  app.kubernetes.io/name: oathkeeper

resources:
  - resources/serviceaccount.yaml
  - resources/deployment.yaml
  - resources/service.yaml

configMapGenerator:
  - name: oathkeeper-config
    files:
      - configs/config.yaml
      - configs/rules.yaml

images:
  - name: oryd/oathkeeper
    newTag: v0.38.23
